spring.application.name=customer-service
spring.jackson.time-zone=America/Guayaquil

# Configuracion de Conexion a Base de Datos
#server.port=8081
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Configuracion de Conexion a RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Tiempos de espera y reconexion opcionales
spring.rabbitmq.connection-timeout=5000ms


