spring.application.name=account-service

# Configuracion de Conexion a Base de Datos
#server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Configuracion de Conexion a RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Tiempos de espera y reconexion opcionales
spring.rabbitmq.connection-timeout=5000ms

#Configuracion de reintentos en caso de fallo al procesar un mensaje
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0

#Inicia la escucha automaticamente
spring.rabbitmq.listener.simple.auto-startup=true

#Propiedad personalizada para el Listener
app.rabbitmq.queue=customer.created.queue